### ISSUE TITLE
Where Clause on Split List

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#338] opened 2023-11-21 11:47 UTC
Can we remove the Where from linting for split.list?  Or some other way to alert user to this limitation?

Get rid of the where: VENDOR != ""
You should have an empty list in those rows anyway, so merging them has no impact with or without the where.

It's a bit of an edge case due to the way we merge the rows that use where back to the original dataframe. We join, then coalesce between the values from the old and new column. In this case the empty list counts as false and it doesn't preserve the value. Not sure if there's a better way we can do that.

**Comment by ChrisWRWX** [comment] 2023-11-21 16:20
Duplicate of #337

**Closed by ChrisWRWX** 2023-11-21 16:20 UTC
Labels: documentation
